<?php

declare(strict_types=1);

namespace MirayS\Onix\CodeList;

/**
 * ONIX Code List 85 — Bible purpose
 *
 * @see https://ns.editeur.org/onix/en/85
 */
class CodeList85 extends CodeList implements CodeListInterface
{
    protected static array $en = [
        'AW' => 'Award',
        'BB' => 'Baby',
        'BR' => 'Bride',
        'CH' => 'Children’s',
        'CT' => 'Christening / Baptism gift',
        'CM' => 'Compact',
        'CF' => 'Confirmation',
        'CR' => 'Cross-reference',
        'DR' => 'Daily readings',
        'DV' => 'Devotional',
        'FM' => 'Family',
        'FC' => 'First communion',
        'GT' => 'General / Text',
        'GF' => 'Gift',
        'JN' => 'Journaling / notetaking',
        'LP' => 'Lectern / Pulpit',
        'MN' => 'Men’s',
        'OT' => 'Outreach',
        'PA' => 'Pastoral',
        'PW' => 'Pew',
        'PR' => 'Preaching',
        'PS' => 'Primary school',
        'RD' => 'Reader’s',
        'SC' => 'Scholarly',
        'SL' => 'Slimline',
        'ST' => 'Student',
        'SU' => 'Study',
        'WG' => 'Wedding gift',
        'WM' => 'Women’s',
        'YT' => 'Youth / Teen',
    ];

    protected static array $es = [
        'AW' => 'Award',
        'BB' => 'Baby',
        'BR' => 'Bride',
        'CF' => 'Confirmation',
        'CH' => 'Children’s',
        'CM' => 'Compact',
        'CR' => 'Cross-reference',
        'DR' => 'Daily readings',
        'DV' => 'Devotional',
        'FM' => 'Family',
        'GT' => 'General / Text',
        'GF' => 'Gift',
        'LP' => 'Lectern / Pulpit',
        'MN' => 'Men’s',
        'PS' => 'Primary school',
        'PW' => 'Pew',
        'SC' => 'Scholarly',
        'SL' => 'Slimline',
        'ST' => 'Student',
        'SU' => 'Study',
        'WG' => 'Wedding gift',
        'WM' => 'Women’s',
        'YT' => 'Youth',
    ];

    protected static array $de = [
        'AW' => 'Award',
        'BB' => 'Baby',
        'BR' => 'Bride',
        'CF' => 'Confirmation',
        'CH' => 'Children’s',
        'CM' => 'Compact',
        'CR' => 'Cross-reference',
        'DR' => 'Daily readings',
        'DV' => 'Devotional',
        'FM' => 'Family',
        'GT' => 'General/Text',
        'GF' => 'Gift',
        'LP' => 'Lectern/Pulpit',
        'MN' => 'Men’s',
        'PS' => 'Primary school',
        'PW' => 'Pew',
        'SC' => 'Scholarly',
        'SL' => 'Slimline',
        'ST' => 'Student',
        'SU' => 'Study',
        'WG' => 'Wedding gift',
        'WM' => 'Women’s',
        'YT' => 'Youth',
    ];

    protected static array $fr = [
        'AW' => 'Prix',
        'BB' => 'Naissance',
        'BR' => 'Mariée',
        'CF' => 'Confirmation',
        'CH' => 'Enfant',
        'CM' => 'Compacte',
        'CR' => 'Avec références',
        'DR' => 'Lecture quotidienne',
        'DV' => 'Dévotion',
        'FM' => 'Famille',
        'GT' => 'Générale / Texte',
        'GF' => 'Cadeau',
        'LP' => 'Lutrin / Pupitre',
        'MN' => 'Pour les hommes',
        'PS' => 'Ecole primaire',
        'PW' => 'De banc',
        'SC' => 'Savante',
        'SL' => 'Mince',
        'ST' => 'Etudiant',
        'SU' => 'D’étude',
        'WG' => 'Cadeau de mariage',
        'WM' => 'Pour les femmes',
        'YT' => 'Jeunesse',
    ];

    protected static array $it = [
        'AW' => 'Premio',
        'BB' => 'Per il neonato',
        'BR' => 'Per la sposa',
        'CF' => 'Per la Cresima',
        'CH' => 'Per i bambini',
        'CM' => 'Compatta',
        'CR' => 'Con riferimenti incrociati',
        'DR' => 'Letture giornaliere',
        'DV' => 'Devozionale',
        'FM' => 'Per la famiglia',
        'GT' => 'Generale/Testo',
        'GF' => 'Dono',
        'LP' => 'Liturgica',
        'MN' => 'Per l’uomo',
        'PS' => 'Per le scuole elementari',
        'PW' => 'Per i banchi della chiesa',
        'SC' => 'Per gli studi superiori',
        'SL' => 'Linea a profilo sottile',
        'ST' => 'Per gli studenti',
        'SU' => 'Per lo studio',
        'WG' => 'Dono di nozze',
        'WM' => 'Per le donne',
        'YT' => 'Per i giovani',
    ];

    protected static array $nb = [
        'AW' => 'Award',
        'BB' => 'Baby',
        'BR' => 'Bride',
        'CF' => 'Confirmation',
        'CH' => 'Children’s',
        'CM' => 'Compact',
        'CR' => 'Cross-reference',
        'DR' => 'Daily readings',
        'DV' => 'Devotional',
        'FM' => 'Family',
        'GT' => 'General/Text',
        'GF' => 'Gift',
        'LP' => 'Lectern/Pulpit',
        'MN' => 'Men’s',
        'PS' => 'Primary school',
        'PW' => 'Pew',
        'SC' => 'Scholarly',
        'SL' => 'Slimline',
        'ST' => 'Student',
        'SU' => 'Study',
        'WG' => 'Wedding gift',
        'WM' => 'Women’s',
        'YT' => 'Youth',
    ];

    protected static array $tr = [
        'AW' => 'Ödül',
        'BB' => 'Bebek',
        'BR' => 'Gelin',
        'CF' => 'Kabul',
        'CH' => 'Çocuk',
        'CM' => 'Yoğun',
        'CR' => 'Çapraz başvuru',
        'DR' => 'Günlük okuma',
        'DV' => 'İbadet',
        'FM' => 'Aile',
        'GT' => 'Genel/Metin',
        'GF' => 'Hediyelik',
        'LP' => 'Kürsü/Rahle',
        'MN' => 'Erkek',
        'PS' => 'İlkokul',
        'PW' => 'Sıra',
        'SC' => 'İlahiyat',
        'SL' => 'İnce',
        'ST' => 'Öğrenci',
        'SU' => 'Şerhli',
        'WG' => 'Düğün armağanı',
        'WM' => 'Kadın',
        'YT' => 'Genç',
    ];

}
