<?php

declare(strict_types=1);

namespace MirayS\Onix\CodeList;

/**
 * ONIX Code List 238 — Brazil educational level
 *
 * @see https://ns.editeur.org/onix/en/238
 */
class CodeList238 extends CodeList implements CodeListInterface
{
    protected static array $en = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura/ Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

    protected static array $es = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura / Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

    protected static array $de = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura/ Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

    protected static array $fr = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura/ Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

    protected static array $it = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura/ Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

    protected static array $nb = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura/ Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

    protected static array $tr = [
        'K' => 'Educação Infantil',
        '1' => 'Fundamental I 1º ano',
        '2' => 'Fundamental I 2º ano',
        '3' => 'Fundamental I 3º ano',
        '4' => 'Fundamental I 4º ano',
        '5' => 'Fundamental I 5º ano',
        '6' => 'Fundamental II 6º ano',
        '7' => 'Fundamental II 7º ano',
        '8' => 'Fundamental II 8º ano',
        '9' => 'Fundamental II 9º ano',
        '10' => 'Ensino Médio 1º ano',
        '11' => 'Ensino Médio 2º ano',
        '12' => 'Ensino Médio 3º ano',
        '13' => 'Ensino Técnico Integrado',
        '14' => 'Ensino Técnico Concomitante',
        '15' => 'Ensino Técnico Subsequente',
        'P' => 'Ensino pré-vestibular',
        'A' => 'Ensino Superior Graduação Licenciatura/ Bacharelado',
        'B' => 'Ensino Superior Graduação Tecnologia',
        'D' => 'Ensino Superior Pós-graduação Stricto sensu',
        'F' => 'Ensino Superior Pós-graduação Lato sensu',
    ];

}
