<?php

declare(strict_types=1);

namespace MirayS\Onix\CodeList;

/**
 * ONIX Code List 98 — Binding or page edge color
 *
 * @see https://ns.editeur.org/onix/en/98
 */
class CodeList98 extends CodeList implements CodeListInterface
{
    protected static array $en = [
        'BLK' => 'Black',
        'BLU' => 'Blue',
        'BRN' => 'Brown',
        'BUR' => 'Burgundy / Maroon',
        'CEL' => 'Celadon / Pale green',
        'CPR' => 'Copper',
        'CRE' => 'Cream',
        'FCO' => 'Four-color',
        'FCS' => 'Four-color and spot-color',
        'GLD' => 'Gold',
        'GRN' => 'Green',
        'GRY' => 'Grey',
        'HOL' => 'Holographic',
        'MUL' => 'Multicolor',
        'NAV' => 'Navy / Dark blue',
        'ORG' => 'Orange',
        'PNK' => 'Pink',
        'PUR' => 'Purple',
        'RED' => 'Red',
        'SKY' => 'Sky / Pale blue',
        'SLV' => 'Silver',
        'TAN' => 'Tan / Light brown',
        'TEA' => 'Teal / Turquoise green',
        'WHI' => 'White',
        'YEL' => 'Yellow',
        'ZZZ' => 'Other',
    ];

    protected static array $es = [
        'BLK' => 'Negro',
        'BLU' => 'Azul',
        'BRN' => 'Marrón',
        'BUR' => 'Burdeos / granate',
        'CEL' => 'Verde pálido / Celadón',
        'CPR' => 'Cobre',
        'CRE' => 'Crema',
        'FCO' => 'Cuatricromía',
        'FCS' => 'Cuatricromía y colores suplementarios (spot-color)',
        'GLD' => 'Dorado',
        'GRN' => 'Verde',
        'GRY' => 'Gris',
        'MUL' => 'Multicolor',
        'NAV' => 'Azul marino',
        'ORG' => 'Naranja',
        'PNK' => 'Rosa',
        'PUR' => 'Violeta / Morado',
        'RED' => 'Rojo',
        'SKY' => 'Azul pálido / Azul cielo',
        'SLV' => 'Plata',
        'TAN' => 'Beige / Habano',
        'TEA' => 'Verde turquesa (en inglés «teal»)',
        'WHI' => 'Blanco',
        'YEL' => 'Amarillo',
        'ZZZ' => 'Otro',
    ];

    protected static array $de = [
        'BLK' => 'Black',
        'BLU' => 'Blue',
        'BRN' => 'Brown',
        'BUR' => 'Burgundy/Maroon',
        'CEL' => 'Celadon/Pale green',
        'CPR' => 'Copper',
        'CRE' => 'Cream',
        'FCO' => 'Four-color',
        'FCS' => 'Four-color and spot-color',
        'GLD' => 'Gold',
        'GRN' => 'Green',
        'GRY' => 'Grey',
        'MUL' => 'Multicolor',
        'NAV' => 'Navy/Dark blue',
        'ORG' => 'Orange',
        'PNK' => 'Pink',
        'PUR' => 'Purple',
        'RED' => 'Red',
        'SKY' => 'Sky/Pale blue',
        'SLV' => 'Silver',
        'TAN' => 'Tan/Light brown',
        'TEA' => 'Teal/Turquoise green',
        'WHI' => 'White',
        'YEL' => 'Yellow',
        'ZZZ' => 'Other',
    ];

    protected static array $fr = [
        'BLK' => 'Noir',
        'BLU' => 'Bleu',
        'BRN' => 'Marron',
        'BUR' => 'Bordeaux',
        'CEL' => 'Vert pâle / Céladon',
        'CPR' => 'Copper',
        'CRE' => 'Crème',
        'FCO' => 'Quatre couleurs',
        'FCS' => 'Quadrichromie et couleur d’accompagnement',
        'GLD' => 'Or',
        'GRN' => 'Vert',
        'GRY' => 'Gris',
        'MUL' => 'Multicolore',
        'NAV' => 'Bleu marine / bleu foncé',
        'ORG' => 'Orange',
        'PNK' => 'Rose',
        'PUR' => 'Violet',
        'RED' => 'Rouge',
        'SKY' => 'Bleu ciel / bleu pâle',
        'SLV' => 'Argent',
        'TAN' => 'Brun',
        'TEA' => 'Bleu vert / Turquoise',
        'WHI' => 'Blanc',
        'YEL' => 'Jaune',
        'ZZZ' => 'Autre',
    ];

    protected static array $it = [
        'BLK' => 'Nero',
        'BLU' => 'Blu',
        'BRN' => 'Marrone',
        'BUR' => 'Rosso borgogna/marrone rossiccio',
        'CEL' => 'Celadon/verde pallido',
        'CPR' => 'Rame',
        'CRE' => 'Crema',
        'FCO' => 'Quadricromia',
        'FCS' => 'Quadricromia e quinto colore',
        'GLD' => 'Oro',
        'GRN' => 'Verde',
        'GRY' => 'Grigio',
        'MUL' => 'Multicolore',
        'NAV' => 'Blu scuro',
        'ORG' => 'Arancione',
        'PNK' => 'Rosa',
        'PUR' => 'Porpora',
        'RED' => 'Rosso',
        'SKY' => 'Celeste',
        'SLV' => 'Argento',
        'TAN' => 'Marrone chiaro',
        'TEA' => 'Foglia di tè/turchese',
        'WHI' => 'Bianco',
        'YEL' => 'Giallo',
        'ZZZ' => 'Altro',
    ];

    protected static array $nb = [
        'BLK' => 'Svart',
        'BLU' => 'Blå',
        'BRN' => 'Brun',
        'BUR' => 'Burgunder',
        'CEL' => 'Celadon/lys grønn',
        'CPR' => 'Kobber',
        'CRE' => 'Krem',
        'FCO' => 'Four-color',
        'FCS' => 'Four-color and spot-color',
        'GLD' => 'Gull',
        'GRN' => 'Grønn',
        'GRY' => 'Grå',
        'MUL' => 'Flerfarget',
        'NAV' => 'Mørk blå',
        'ORG' => 'Oransje',
        'PNK' => 'Rosa',
        'PUR' => 'Fiolett',
        'RED' => 'Rød',
        'SKY' => 'Lys blå',
        'SLV' => 'Sølv',
        'TAN' => 'Lys brun',
        'TEA' => 'Turkis',
        'WHI' => 'Hvit',
        'YEL' => 'Gul',
        'ZZZ' => 'Andre',
    ];

    protected static array $tr = [
        'BLK' => 'Siyah',
        'BLU' => 'Mavi',
        'BRN' => 'Kahverengi',
        'BUR' => 'Bordo/şarabi',
        'CEL' => 'Celadon/Pale green',
        'CPR' => 'Copper',
        'CRE' => 'Krem',
        'FCO' => 'Dört renk',
        'FCS' => 'Dört renk ve spot renk',
        'GLD' => 'Yaldız',
        'GRN' => 'Yeşil',
        'GRY' => 'Gri',
        'MUL' => 'Çok renkli',
        'NAV' => 'Lacivert/Koyu mavi',
        'ORG' => 'Turuncu',
        'PNK' => 'Pembe',
        'PUR' => 'Mor',
        'RED' => 'Kırmızı',
        'SKY' => 'Gök mavisi/Soluk mavi',
        'SLV' => 'Gümüş',
        'TAN' => 'Taba',
        'TEA' => 'Camgöbeği/Turkuaz yeşili',
        'WHI' => 'Beyaz',
        'YEL' => 'Sarı',
        'ZZZ' => 'Diğer',
    ];

}
