<?php

declare(strict_types=1);

namespace MirayS\Onix\CodeList;

/**
 * ONIX Code List 5 — Product identifier type
 *
 * @see https://ns.editeur.org/onix/en/5
 */
class CodeList5 extends CodeList implements CodeListInterface
{
    protected static array $en = [
        '01' => 'Proprietary product ID scheme',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN-10',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Legal deposit number',
        '22' => 'URN',
        '23' => 'OCLC number',
        '24' => 'Co-publisher’s ISBN-13',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'JP e-code',
        '28' => 'OLCC number',
        '29' => 'JP Magazine ID',
        '30' => 'UPC-12+5',
        '31' => 'BNF Control number',
        '34' => 'ISSN-13',
        '35' => 'ARK',
        '36' => 'Digital file internal version number',
    ];

    protected static array $es = [
        '01' => 'Propio / Privado',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN-10',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Depósito Legal',
        '22' => 'URN',
        '23' => 'Número OCLC',
        '24' => 'ISBN-13 asignado por una coeditorial',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'Código JP e-code',
        '28' => 'Número de OLCC',
        '29' => 'Identificador JP Magazine',
        '30' => 'UPC12+5',
        '31' => 'Número de control de la BNF',
        '35' => 'ARK',
    ];

    protected static array $de = [
        '01' => 'Proprietary',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN-10',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Legal deposit number',
        '22' => 'URN',
        '23' => 'OCLC number',
        '24' => 'Co-publisher’s ISBN-13',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'JP e-code',
        '28' => 'OLCC number',
        '29' => 'JP Magazine ID',
        '30' => 'UPC12+5',
        '31' => 'BNF Control number',
        '35' => 'ARK',
    ];

    protected static array $fr = [
        '01' => 'Propriétaire',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN-10',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Numéro de dépôt légal',
        '22' => 'URN',
        '23' => 'Numéro OCLC',
        '24' => 'Numéro ISBN-13 du coéditeur',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'JP e-code',
        '28' => 'Numéro OLCC',
        '29' => 'JP Magazine ID',
        '30' => 'UPC12+5',
        '31' => 'Numéro BnF',
        '35' => 'ARK',
    ];

    protected static array $it = [
        '01' => 'Proprietario',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN-10',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Numero di deposito legale',
        '22' => 'URN',
        '23' => 'Numero OCLC',
        '24' => 'Codice ISBN-13 del co-editore',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'Codice elettronico JP',
        '28' => 'Numero OLCC',
        '29' => 'JP Magazine ID',
        '30' => 'UPC12+5',
        '31' => 'Numero di controllo BNF',
        '35' => 'ARK',
    ];

    protected static array $nb = [
        '01' => 'Proprietær',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Legal deposit number',
        '22' => 'URN',
        '23' => 'OCLC number',
        '24' => 'Medutgivers ISBN-13',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'JP e-code',
        '28' => 'OLCC nummer',
        '29' => 'JP Magazine ID',
        '30' => 'UPC 12+5',
        '31' => 'BNF control number',
        '35' => 'ARK',
    ];

    protected static array $tr = [
        '01' => 'Özel',
        '02' => 'ISBN-10',
        '03' => 'GTIN-13',
        '04' => 'UPC',
        '05' => 'ISMN-10',
        '06' => 'DOI',
        '13' => 'LCCN',
        '14' => 'GTIN-14',
        '15' => 'ISBN-13',
        '17' => 'Derleme nüshası numarası',
        '22' => 'URN',
        '23' => 'OCLC numarası',
        '24' => 'Ortak yayımcı ISBN-13’ü',
        '25' => 'ISMN-13',
        '26' => 'ISBN-A',
        '27' => 'JP e-kodu',
        '28' => 'OLCC numarası',
        '29' => 'JP Dergi Tanımlayıcı',
        '30' => 'UPC12 + 5',
        '31' => 'BNF Control number',
        '35' => 'ARK',
    ];

}
