<?php

declare(strict_types=1);

namespace MirayS\Onix\Schema;

final class ElementSchema
{
    private const ELEMENTS = [
        'ONIXMessage' => ['short' => 'ONIXmessage', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Message\\Message'],
        'Addressee' => ['short' => 'addressee', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Message\\Addressee'],
        'AddresseeIdentifier' => ['short' => 'addresseeidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Message\\AddresseeIdentifier'],
        'AddresseeIDType' => ['short' => 'm380', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AddresseeName' => ['short' => 'x300', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Affiliation' => ['short' => 'b046', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AffiliationIdentifier' => ['short' => 'affiliationidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.1'], 'class' => 'MirayS\Onix\Product\\AffiliationIdentifier'],
        'AffiliationIDType' => ['short' => 'x580', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.1'], 'class' => null],
        'AgentIdentifier' => ['short' => 'agentidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\AgentIdentifier'],
        'AgentIDType' => ['short' => 'j400', 'kind' => 'codelist', 'codelist' => '92', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AgentName' => ['short' => 'j401', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AgentRole' => ['short' => 'j402', 'kind' => 'codelist', 'codelist' => '69', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AlternativeName' => ['short' => 'alternativename', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\AlternativeName'],
        'AncillaryContent' => ['short' => 'ancillarycontent', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\AncillaryContent'],
        'AncillaryContentDescription' => ['short' => 'x424', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AncillaryContentType' => ['short' => 'x423', 'kind' => 'codelist', 'codelist' => '25', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Audience' => ['short' => 'audience', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Audience'],
        'AudienceCodeType' => ['short' => 'b204', 'kind' => 'codelist', 'codelist' => '29', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceCodeTypeName' => ['short' => 'b205', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceCodeValue' => ['short' => 'b206', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceDescription' => ['short' => 'b207', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceHeadingText' => ['short' => 'x578', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceRange' => ['short' => 'audiencerange', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\AudienceRange'],
        'AudienceRangePrecision' => ['short' => 'b075', 'kind' => 'codelist', 'codelist' => '31', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceRangeQualifier' => ['short' => 'b074', 'kind' => 'codelist', 'codelist' => '30', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceRangeValue' => ['short' => 'b076', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AVDuration' => ['short' => 'x544', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AVItem' => ['short' => 'avitem', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\AVItem'],
        'AVItemIdentifier' => ['short' => 'avitemidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\AVItemIdentifier'],
        'AVItemIDType' => ['short' => 'x541', 'kind' => 'codelist', 'codelist' => '241', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AVItemType' => ['short' => 'x540', 'kind' => 'codelist', 'codelist' => '240', 'releases' => ['3.0', '3.1'], 'class' => null],
        'AwardingBody' => ['short' => 'x584', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'Barcode' => ['short' => 'barcode', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Barcode'],
        'BarcodeType' => ['short' => 'x312', 'kind' => 'codelist', 'codelist' => '141', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BatchBonus' => ['short' => 'batchbonus', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\BatchBonus'],
        'BatchQuantity' => ['short' => 'j264', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Bible' => ['short' => 'bible', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Bible'],
        'BibleContents' => ['short' => 'b352', 'kind' => 'codelist', 'codelist' => '82', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BiblePurpose' => ['short' => 'b354', 'kind' => 'codelist', 'codelist' => '85', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BibleReferenceLocation' => ['short' => 'b356', 'kind' => 'codelist', 'codelist' => '87', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BibleTextFeature' => ['short' => 'b357', 'kind' => 'codelist', 'codelist' => '97', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BibleTextOrganization' => ['short' => 'b355', 'kind' => 'codelist', 'codelist' => '86', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BibleVersion' => ['short' => 'b353', 'kind' => 'codelist', 'codelist' => '83', 'releases' => ['3.0', '3.1'], 'class' => null],
        'BiographicalNote' => ['short' => 'b044', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'BodyManifest' => ['short' => 'bodymanifest', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\BodyManifest'],
        'BodyResource' => ['short' => 'bodyresource', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\BodyResource'],
        'BookClubAdoption' => ['short' => 'k169', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CBO' => ['short' => 'j375', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CitationNote' => ['short' => 'x434', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CitedContent' => ['short' => 'citedcontent', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CitedContent'],
        'CitedContentType' => ['short' => 'x430', 'kind' => 'codelist', 'codelist' => '156', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CityOfPublication' => ['short' => 'b209', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CollateralDetail' => ['short' => 'collateraldetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CollateralDetail'],
        'Collection' => ['short' => 'collection', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Collection'],
        'CollectionElementLevel' => ['short' => 'x586', 'kind' => 'codelist', 'codelist' => '149', 'releases' => ['3.1'], 'class' => null],
        'CollectionFrequency' => ['short' => 'x582', 'kind' => 'codelist', 'codelist' => '259', 'releases' => ['3.1'], 'class' => null],
        'CollectionIdentifier' => ['short' => 'collectionidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CollectionIdentifier'],
        'CollectionIDType' => ['short' => 'x344', 'kind' => 'codelist', 'codelist' => '13', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CollectionSequence' => ['short' => 'collectionsequence', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CollectionSequence'],
        'CollectionSequenceNumber' => ['short' => 'x481', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CollectionSequenceType' => ['short' => 'x479', 'kind' => 'codelist', 'codelist' => '197', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CollectionSequenceTypeName' => ['short' => 'x480', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CollectionType' => ['short' => 'x329', 'kind' => 'codelist', 'codelist' => '148', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ComparisonProductPrice' => ['short' => 'comparisonproductprice', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ComparisonProductPrice'],
        'Complexity' => ['short' => 'complexity', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Complexity'],
        'ComplexityCode' => ['short' => 'b078', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ComplexitySchemeIdentifier' => ['short' => 'b077', 'kind' => 'codelist', 'codelist' => '32', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ComponentNumber' => ['short' => 'b289', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ComponentTypeName' => ['short' => 'b288', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContactName' => ['short' => 'x299', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContentAudience' => ['short' => 'x427', 'kind' => 'codelist', 'codelist' => '154', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContentDate' => ['short' => 'contentdate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ContentDate'],
        'ContentDateRole' => ['short' => 'x429', 'kind' => 'codelist', 'codelist' => '155', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContentDetail' => ['short' => 'contentdetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ContentDetail'],
        'ContentItem' => ['short' => 'contentitem', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ContentItem'],
        'Contributor' => ['short' => 'contributor', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Contributor'],
        'ContributorDate' => ['short' => 'contributordate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ContributorDate'],
        'ContributorDateRole' => ['short' => 'x417', 'kind' => 'codelist', 'codelist' => '177', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContributorDescription' => ['short' => 'b048', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContributorPlace' => ['short' => 'contributorplace', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ContributorPlace'],
        'ContributorPlaceRelator' => ['short' => 'x418', 'kind' => 'codelist', 'codelist' => '151', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContributorReference' => ['short' => 'contributorreference', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ContributorReference'],
        'ContributorRole' => ['short' => 'b035', 'kind' => 'codelist', 'codelist' => '17', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ContributorStatement' => ['short' => 'b049', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CopiesSold' => ['short' => 'k168', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CopyrightOwner' => ['short' => 'copyrightowner', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CopyrightOwner'],
        'CopyrightOwnerIdentifier' => ['short' => 'copyrightowneridentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CopyrightOwnerIdentifier'],
        'CopyrightOwnerIDType' => ['short' => 'b392', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CopyrightStatement' => ['short' => 'copyrightstatement', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CopyrightStatement'],
        'CopyrightStatementText' => ['short' => 'x588', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'CopyrightType' => ['short' => 'x512', 'kind' => 'codelist', 'codelist' => '219', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CopyrightYear' => ['short' => 'b087', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CorporateName' => ['short' => 'b047', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CorporateNameInverted' => ['short' => 'x443', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CountriesIncluded' => ['short' => 'x449', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CountriesExcluded' => ['short' => 'x451', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'CountryCode' => ['short' => 'b251', 'kind' => 'codelist', 'codelist' => '91', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CountryOfManufacture' => ['short' => 'x316', 'kind' => 'codelist', 'codelist' => '91', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CountryOfPublication' => ['short' => 'b083', 'kind' => 'codelist', 'codelist' => '91', 'releases' => ['3.0', '3.1'], 'class' => null],
        'CoverManifest' => ['short' => 'covermanifest', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CoverManifest'],
        'CoverResource' => ['short' => 'coverresource', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\CoverResource'],
        'CurrencyCode' => ['short' => 'j152', 'kind' => 'codelist', 'codelist' => '96', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Date' => ['short' => 'b306', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'DefaultCurrencyCode' => ['short' => 'm186', 'kind' => 'codelist', 'codelist' => '96', 'releases' => ['3.0', '3.1'], 'class' => null],
        'DefaultLanguageOfText' => ['short' => 'm184', 'kind' => 'codelist', 'codelist' => '74', 'releases' => ['3.0', '3.1'], 'class' => null],
        'DefaultPriceType' => ['short' => 'x310', 'kind' => 'codelist', 'codelist' => '58', 'releases' => ['3.0', '3.1'], 'class' => null],
        'DeletionText' => ['short' => 'a199', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'DescriptiveDetail' => ['short' => 'descriptivedetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\DescriptiveDetail'],
        'Discount' => ['short' => 'discount', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Discount'],
        'DiscountAmount' => ['short' => 'x469', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'DiscountCode' => ['short' => 'j364', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'DiscountCoded' => ['short' => 'discountcoded', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\DiscountCoded'],
        'DiscountCodeType' => ['short' => 'j363', 'kind' => 'codelist', 'codelist' => '100', 'releases' => ['3.0', '3.1'], 'class' => null],
        'DiscountCodeTypeName' => ['short' => 'j378', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'DiscountPercent' => ['short' => 'j267', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'DiscountType' => ['short' => 'x467', 'kind' => 'codelist', 'codelist' => '170', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EditionNumber' => ['short' => 'b057', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EditionStatement' => ['short' => 'b058', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EditionType' => ['short' => 'x419', 'kind' => 'codelist', 'codelist' => '21', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EditionVersionNumber' => ['short' => 'b217', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EmailAddress' => ['short' => 'j272', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EndDate' => ['short' => 'b325', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EndTime' => ['short' => 'x543', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubLicenseDate' => ['short' => 'epublicensedate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.1'], 'class' => 'MirayS\Onix\Product\\EpubLicenseDate'],
        'EpubLicenseDateRole' => ['short' => 'x585', 'kind' => 'codelist', 'codelist' => '260', 'releases' => ['3.1'], 'class' => null],
        'EpubLicenseExpression' => ['short' => 'epublicenseexpression', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EpubLicenseExpression'],
        'EpubLicenseExpressionLink' => ['short' => 'x510', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubLicenseExpressionType' => ['short' => 'x508', 'kind' => 'codelist', 'codelist' => '218', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubLicenseExpressionTypeName' => ['short' => 'x509', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubLicenseName' => ['short' => 'x511', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubTechnicalProtection' => ['short' => 'x317', 'kind' => 'codelist', 'codelist' => '144', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubUsageConstraint' => ['short' => 'epubusageconstraint', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EpubUsageConstraint'],
        'EpubUsageLimit' => ['short' => 'epubusagelimit', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EpubUsageLimit'],
        'EpubUsageStatus' => ['short' => 'x319', 'kind' => 'codelist', 'codelist' => '146', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubUsageType' => ['short' => 'x318', 'kind' => 'codelist', 'codelist' => '145', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EpubUsageUnit' => ['short' => 'x321', 'kind' => 'codelist', 'codelist' => '147', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Event' => ['short' => 'event', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Event'],
        'EventAcronym' => ['short' => 'x517', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventDate' => ['short' => 'x520', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventDescription' => ['short' => 'x550', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventIdentifier' => ['short' => 'eventidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EventIdentifier'],
        'EventIDType' => ['short' => 'x547', 'kind' => 'codelist', 'codelist' => '244', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventName' => ['short' => 'x516', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventNumber' => ['short' => 'x518', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventOccurrence' => ['short' => 'eventoccurrence', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EventOccurrence'],
        'EventPlace' => ['short' => 'x521', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventRole' => ['short' => 'x515', 'kind' => 'codelist', 'codelist' => '20', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventSponsor' => ['short' => 'eventsponsor', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EventSponsor'],
        'EventSponsorIdentifier' => ['short' => 'eventsponsoridentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\EventSponsorIdentifier'],
        'EventSponsorIDType' => ['short' => 'x522', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventStatus' => ['short' => 'x549', 'kind' => 'codelist', 'codelist' => '246', 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventTheme' => ['short' => 'x519', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'EventType' => ['short' => 'x548', 'kind' => 'codelist', 'codelist' => '245', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ExpectedDate' => ['short' => 'j302', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Extent' => ['short' => 'extent', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Extent'],
        'ExtentType' => ['short' => 'b218', 'kind' => 'codelist', 'codelist' => '23', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ExtentUnit' => ['short' => 'b220', 'kind' => 'codelist', 'codelist' => '24', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ExtentValue' => ['short' => 'b219', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ExtentValueRoman' => ['short' => 'x421', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'FaxNumber' => ['short' => 'j271', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'FeatureNote' => ['short' => 'x440', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'FeatureValue' => ['short' => 'x439', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'FirstPageNumber' => ['short' => 'b286', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'FreeQuantity' => ['short' => 'j265', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'FromLanguage' => ['short' => 'x412', 'kind' => 'codelist', 'codelist' => '74', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Funding' => ['short' => 'funding', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Funding'],
        'FundingIdentifier' => ['short' => 'fundingidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\FundingIdentifier'],
        'FundingIDType' => ['short' => 'x523', 'kind' => 'codelist', 'codelist' => '228', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Header' => ['short' => 'header', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Message\\Header'],
        'IDTypeName' => ['short' => 'b233', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'IDValue' => ['short' => 'b244', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Illustrated' => ['short' => 'x422', 'kind' => 'codelist', 'codelist' => '152', 'releases' => ['3.0', '3.1'], 'class' => null],
        'IllustrationsNote' => ['short' => 'b062', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Imprint' => ['short' => 'imprint', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Imprint'],
        'ImprintIdentifier' => ['short' => 'imprintidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ImprintIdentifier'],
        'ImprintIDType' => ['short' => 'x445', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ImprintName' => ['short' => 'b079', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ImprintNameInverted' => ['short' => 'x593', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'InitialPrintRun' => ['short' => 'k167', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'InsertManifest' => ['short' => 'insertmanifest', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\InsertManifest'],
        'InsertPoint' => ['short' => 'insertpoint', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\InsertPoint'],
        'InsertPointType' => ['short' => 'x574', 'kind' => 'codelist', 'codelist' => '255', 'releases' => ['3.0', '3.1'], 'class' => null],
        'InsertPointValue' => ['short' => 'x575', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'InsertResource' => ['short' => 'insertresource', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\InsertResource'],
        'KeyNames' => ['short' => 'b040', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Language' => ['short' => 'language', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Language'],
        'LanguageCode' => ['short' => 'b252', 'kind' => 'codelist', 'codelist' => '74', 'releases' => ['3.0', '3.1'], 'class' => null],
        'LanguageRole' => ['short' => 'b253', 'kind' => 'codelist', 'codelist' => '22', 'releases' => ['3.0', '3.1'], 'class' => null],
        'LastPageNumber' => ['short' => 'b287', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'LatestReprintNumber' => ['short' => 'x446', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'LettersAfterNames' => ['short' => 'b042', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'LevelSequenceNumber' => ['short' => 'b284', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ListName' => ['short' => 'x432', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'LocationIdentifier' => ['short' => 'locationidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\LocationIdentifier'],
        'LocationIDType' => ['short' => 'j377', 'kind' => 'codelist', 'codelist' => '92', 'releases' => ['3.0', '3.1'], 'class' => null],
        'LocationName' => ['short' => 'j349', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MainAudience' => ['short' => 'x583', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'MainSubject' => ['short' => 'x425', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MapScale' => ['short' => 'b063', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Market' => ['short' => 'market', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Market'],
        'MarketDate' => ['short' => 'marketdate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\MarketDate'],
        'MarketDateRole' => ['short' => 'j408', 'kind' => 'codelist', 'codelist' => '163', 'releases' => ['3.0', '3.1'], 'class' => null],
        'MarketPublishingDetail' => ['short' => 'marketpublishingdetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\MarketPublishingDetail'],
        'MarketPublishingStatus' => ['short' => 'j407', 'kind' => 'codelist', 'codelist' => '68', 'releases' => ['3.0', '3.1'], 'class' => null],
        'MarketPublishingStatusNote' => ['short' => 'x406', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MarketReference' => ['short' => 'x587', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'Measure' => ['short' => 'measure', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Measure'],
        'Measurement' => ['short' => 'c094', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MeasureType' => ['short' => 'x315', 'kind' => 'codelist', 'codelist' => '48', 'releases' => ['3.0', '3.1'], 'class' => null],
        'MeasureUnitCode' => ['short' => 'c095', 'kind' => 'codelist', 'codelist' => '50', 'releases' => ['3.0', '3.1'], 'class' => null],
        'MessageNote' => ['short' => 'm183', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MessageNumber' => ['short' => 'm180', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MessageRepeat' => ['short' => 'm181', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'MinimumOrderQuantity' => ['short' => 'j263', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NameAsSubject' => ['short' => 'nameassubject', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\NameAsSubject'],
        'NameIdentifier' => ['short' => 'nameidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\NameIdentifier'],
        'NameIDType' => ['short' => 'x415', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'NamesAfterKey' => ['short' => 'b041', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NamesBeforeKey' => ['short' => 'b039', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NameType' => ['short' => 'x414', 'kind' => 'codelist', 'codelist' => '18', 'releases' => ['3.0', '3.1'], 'class' => null],
        'NewSupplier' => ['short' => 'newsupplier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\NewSupplier'],
        'NoCollection' => ['short' => 'x411', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NoContributor' => ['short' => 'n339', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NoEdition' => ['short' => 'n386', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NoPrefix' => ['short' => 'x501', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NoProduct' => ['short' => 'x507', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NoResource' => ['short' => 'x577', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NoSupplement' => ['short' => 'x579', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NotificationType' => ['short' => 'a002', 'kind' => 'codelist', 'codelist' => '1', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Number' => ['short' => 'b257', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NumberOfCopies' => ['short' => 'x323', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NumberOfIllustrations' => ['short' => 'b125', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NumberOfItemsOfThisForm' => ['short' => 'x322', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'NumberOfPages' => ['short' => 'b061', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'OccurrenceDate' => ['short' => 'occurrencedate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\OccurrenceDate'],
        'OccurrenceDateRole' => ['short' => 'x554', 'kind' => 'codelist', 'codelist' => '247', 'releases' => ['3.0', '3.1'], 'class' => null],
        'OnHand' => ['short' => 'j350', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'OnOrder' => ['short' => 'j351', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'OnOrderDetail' => ['short' => 'onorderdetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\OnOrderDetail'],
        'OrderQuantityMinimum' => ['short' => 'x532', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'OrderQuantityMultiple' => ['short' => 'x533', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'OrderTime' => ['short' => 'j144', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PackQuantity' => ['short' => 'j145', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PageRun' => ['short' => 'pagerun', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PageRun'],
        'PalletQuantity' => ['short' => 'x545', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PartNumber' => ['short' => 'x410', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Percent' => ['short' => 'b337', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PersonName' => ['short' => 'b036', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PersonNameInverted' => ['short' => 'b037', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PositionOnList' => ['short' => 'x433', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PositionOnProduct' => ['short' => 'x313', 'kind' => 'codelist', 'codelist' => '142', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PostalCode' => ['short' => 'x590', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'PrefixToKey' => ['short' => 'b247', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Price' => ['short' => 'price', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Price'],
        'PriceAmount' => ['short' => 'j151', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceCode' => ['short' => 'x468', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceCoded' => ['short' => 'pricecoded', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceCoded'],
        'PriceCodeType' => ['short' => 'x465', 'kind' => 'codelist', 'codelist' => '179', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceCodeTypeName' => ['short' => 'x477', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceCondition' => ['short' => 'pricecondition', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceCondition'],
        'PriceConditionQuantity' => ['short' => 'priceconditionquantity', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceConditionQuantity'],
        'PriceConditionQuantityType' => ['short' => 'x464', 'kind' => 'codelist', 'codelist' => '168', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceConditionType' => ['short' => 'x463', 'kind' => 'codelist', 'codelist' => '167', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceConstraint' => ['short' => 'priceconstraint', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceConstraint'],
        'PriceConstraintLimit' => ['short' => 'priceconstraintlimit', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceConstraintLimit'],
        'PriceConstraintStatus' => ['short' => 'x530', 'kind' => 'codelist', 'codelist' => '146', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceConstraintType' => ['short' => 'x529', 'kind' => 'codelist', 'codelist' => '230', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceConstraintUnit' => ['short' => 'x531', 'kind' => 'codelist', 'codelist' => '147', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceDate' => ['short' => 'pricedate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceDate'],
        'PriceDateRole' => ['short' => 'x476', 'kind' => 'codelist', 'codelist' => '173', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceIdentifier' => ['short' => 'priceidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PriceIdentifier'],
        'PriceIDType' => ['short' => 'x506', 'kind' => 'codelist', 'codelist' => '217', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PricePartDescription' => ['short' => 'x535', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PricePer' => ['short' => 'j239', 'kind' => 'codelist', 'codelist' => '60', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceQualifier' => ['short' => 'j261', 'kind' => 'codelist', 'codelist' => '59', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceStatus' => ['short' => 'j266', 'kind' => 'codelist', 'codelist' => '61', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceType' => ['short' => 'x462', 'kind' => 'codelist', 'codelist' => '58', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PriceTypeDescription' => ['short' => 'j262', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrimaryContentType' => ['short' => 'x416', 'kind' => 'codelist', 'codelist' => '81', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrimaryPart' => ['short' => 'x457', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrintedOnProduct' => ['short' => 'x301', 'kind' => 'codelist', 'codelist' => '174', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Prize' => ['short' => 'prize', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Prize'],
        'PrizeCode' => ['short' => 'g129', 'kind' => 'codelist', 'codelist' => '41', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrizeCountry' => ['short' => 'g128', 'kind' => 'codelist', 'codelist' => '91', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrizeIdentifier' => ['short' => 'prizeidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.1'], 'class' => 'MirayS\Onix\Product\\PrizeIdentifier'],
        'PrizeIDType' => ['short' => 'x589', 'kind' => 'codelist', 'codelist' => '263', 'releases' => ['3.1'], 'class' => null],
        'PrizeJury' => ['short' => 'g343', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrizeName' => ['short' => 'g126', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrizeRegion' => ['short' => 'x556', 'kind' => 'codelist', 'codelist' => '49', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrizeStatement' => ['short' => 'x503', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PrizeYear' => ['short' => 'g127', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Product' => ['short' => 'product', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Product'],
        'ProductAvailability' => ['short' => 'j396', 'kind' => 'codelist', 'codelist' => '65', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductClassification' => ['short' => 'productclassification', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductClassification'],
        'ProductClassificationCode' => ['short' => 'b275', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductClassificationType' => ['short' => 'b274', 'kind' => 'codelist', 'codelist' => '9', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductClassificationTypeName' => ['short' => 'x555', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductComposition' => ['short' => 'x314', 'kind' => 'codelist', 'codelist' => '2', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductContact' => ['short' => 'productcontact', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductContact'],
        'ProductContactIdentifier' => ['short' => 'productcontactidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductContactIdentifier'],
        'ProductContactIDType' => ['short' => 'x483', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductContactName' => ['short' => 'x484', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductContactRole' => ['short' => 'x482', 'kind' => 'codelist', 'codelist' => '198', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductContentType' => ['short' => 'b385', 'kind' => 'codelist', 'codelist' => '81', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductForm' => ['short' => 'b012', 'kind' => 'codelist', 'codelist' => '150', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductFormDescription' => ['short' => 'b014', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductFormDetail' => ['short' => 'b333', 'kind' => 'codelist', 'codelist' => '175', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductFormFeature' => ['short' => 'productformfeature', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductFormFeature'],
        'ProductFormFeatureDescription' => ['short' => 'b336', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductFormFeatureType' => ['short' => 'b334', 'kind' => 'codelist', 'codelist' => '79', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductFormFeatureValue' => ['short' => 'b335', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductIdentifier' => ['short' => 'productidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductIdentifier'],
        'ProductIDType' => ['short' => 'b221', 'kind' => 'codelist', 'codelist' => '5', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductionDetail' => ['short' => 'productiondetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductionDetail'],
        'ProductionManifest' => ['short' => 'productionmanifest', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductionManifest'],
        'ProductPackaging' => ['short' => 'b225', 'kind' => 'codelist', 'codelist' => '80', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductPart' => ['short' => 'productpart', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductPart'],
        'ProductRelationCode' => ['short' => 'x455', 'kind' => 'codelist', 'codelist' => '51', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ProductSupply' => ['short' => 'productsupply', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProductSupply'],
        'ProfessionalAffiliation' => ['short' => 'professionalaffiliation', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ProfessionalAffiliation'],
        'ProfessionalPosition' => ['short' => 'b045', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PromotionalEvent' => ['short' => 'promotionalevent', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PromotionalEvent'],
        'PromotionCampaign' => ['short' => 'k165', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PromotionDetail' => ['short' => 'promotiondetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PromotionDetail'],
        'Proximity' => ['short' => 'x502', 'kind' => 'codelist', 'codelist' => '215', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Publisher' => ['short' => 'publisher', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Publisher'],
        'PublisherIdentifier' => ['short' => 'publisheridentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PublisherIdentifier'],
        'PublisherIDType' => ['short' => 'x447', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PublisherName' => ['short' => 'b081', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'PublisherNameInverted' => ['short' => 'x592', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'PublisherRepresentative' => ['short' => 'publisherrepresentative', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PublisherRepresentative'],
        'PublishingDate' => ['short' => 'publishingdate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PublishingDate'],
        'PublishingDateRole' => ['short' => 'x448', 'kind' => 'codelist', 'codelist' => '163', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PublishingDetail' => ['short' => 'publishingdetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\PublishingDetail'],
        'PublishingRole' => ['short' => 'b291', 'kind' => 'codelist', 'codelist' => '45', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PublishingStatus' => ['short' => 'b394', 'kind' => 'codelist', 'codelist' => '64', 'releases' => ['3.0', '3.1'], 'class' => null],
        'PublishingStatusNote' => ['short' => 'b395', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Quantity' => ['short' => 'x320', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'QuantityUnit' => ['short' => 'x466', 'kind' => 'codelist', 'codelist' => '169', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Rate' => ['short' => 'x505', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Rating' => ['short' => 'x525', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RatingLimit' => ['short' => 'x526', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RatingUnits' => ['short' => 'x527', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RecordReference' => ['short' => 'a001', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RecordSourceIdentifier' => ['short' => 'recordsourceidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\RecordSourceIdentifier'],
        'RecordSourceIDType' => ['short' => 'x311', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'RecordSourceName' => ['short' => 'a197', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RecordSourceType' => ['short' => 'a194', 'kind' => 'codelist', 'codelist' => '3', 'releases' => ['3.0', '3.1'], 'class' => null],
        'RegionCode' => ['short' => 'b398', 'kind' => 'codelist', 'codelist' => '49', 'releases' => ['3.0', '3.1'], 'class' => null],
        'RegionsIncluded' => ['short' => 'x450', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RegionsExcluded' => ['short' => 'x452', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'RelatedMaterial' => ['short' => 'relatedmaterial', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\RelatedMaterial'],
        'RelatedProduct' => ['short' => 'relatedproduct', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\RelatedProduct'],
        'RelatedWork' => ['short' => 'relatedwork', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\RelatedWork'],
        'ReligiousText' => ['short' => 'religioustext', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ReligiousText'],
        'ReligiousTextFeature' => ['short' => 'religioustextfeature', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ReligiousTextFeature'],
        'ReligiousTextFeatureCode' => ['short' => 'b359', 'kind' => 'codelist', 'codelist' => '90', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReligiousTextFeatureDescription' => ['short' => 'b360', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReligiousTextFeatureType' => ['short' => 'b358', 'kind' => 'codelist', 'codelist' => '89', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReligiousTextIdentifier' => ['short' => 'b376', 'kind' => 'codelist', 'codelist' => '88', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReprintDetail' => ['short' => 'k309', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Reserved' => ['short' => 'x536', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceContentType' => ['short' => 'x436', 'kind' => 'codelist', 'codelist' => '158', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFeature' => ['short' => 'resourcefeature', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ResourceFeature'],
        'ResourceFeatureType' => ['short' => 'x438', 'kind' => 'codelist', 'codelist' => '160', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileContentDescription' => ['short' => 'x576', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileDate' => ['short' => 'resourcefiledate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ResourceFileDate'],
        'ResourceFileDateRole' => ['short' => 'x573', 'kind' => 'codelist', 'codelist' => '254', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileDescription' => ['short' => 'x571', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileDetail' => ['short' => 'x567', 'kind' => 'codelist', 'codelist' => '252', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileFeature' => ['short' => 'resourcefilefeature', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ResourceFileFeature'],
        'ResourceFileFeatureDescription' => ['short' => 'x570', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileFeatureType' => ['short' => 'x568', 'kind' => 'codelist', 'codelist' => '253', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileFeatureValue' => ['short' => 'x569', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceFileLink' => ['short' => 'x572', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceForm' => ['short' => 'x441', 'kind' => 'codelist', 'codelist' => '161', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceIdentifier' => ['short' => 'resourceidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ResourceIdentifier'],
        'ResourceIDType' => ['short' => 'x565', 'kind' => 'codelist', 'codelist' => '250', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceLink' => ['short' => 'x435', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceMode' => ['short' => 'x437', 'kind' => 'codelist', 'codelist' => '159', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceRole' => ['short' => 'x566', 'kind' => 'codelist', 'codelist' => '251', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ResourceVersion' => ['short' => 'resourceversion', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ResourceVersion'],
        'ResourceVersionFeature' => ['short' => 'resourceversionfeature', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ResourceVersionFeature'],
        'ResourceVersionFeatureType' => ['short' => 'x442', 'kind' => 'codelist', 'codelist' => '162', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReturnsCode' => ['short' => 'j269', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReturnsCodeType' => ['short' => 'j268', 'kind' => 'codelist', 'codelist' => '53', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReturnsCodeTypeName' => ['short' => 'x460', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReturnsConditions' => ['short' => 'returnsconditions', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ReturnsConditions'],
        'ReturnsNote' => ['short' => 'x528', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ReviewRating' => ['short' => 'reviewrating', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\ReviewRating'],
        'ROWSalesRightsType' => ['short' => 'x456', 'kind' => 'codelist', 'codelist' => '46', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SalesOutlet' => ['short' => 'salesoutlet', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SalesOutlet'],
        'SalesOutletIdentifier' => ['short' => 'salesoutletidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SalesOutletIdentifier'],
        'SalesOutletIDType' => ['short' => 'b393', 'kind' => 'codelist', 'codelist' => '102', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SalesOutletName' => ['short' => 'b382', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SalesRestriction' => ['short' => 'salesrestriction', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SalesRestriction'],
        'SalesRestrictionNote' => ['short' => 'x453', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SalesRestrictionType' => ['short' => 'b381', 'kind' => 'codelist', 'codelist' => '71', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SalesRights' => ['short' => 'salesrights', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SalesRights'],
        'SalesRightsType' => ['short' => 'b089', 'kind' => 'codelist', 'codelist' => '46', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ScriptCode' => ['short' => 'x420', 'kind' => 'codelist', 'codelist' => '121', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Sender' => ['short' => 'sender', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Message\\Sender'],
        'SenderIdentifier' => ['short' => 'senderidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Message\\SenderIdentifier'],
        'SenderIDType' => ['short' => 'm379', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SenderName' => ['short' => 'x298', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SentDateTime' => ['short' => 'x307', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SequenceNumber' => ['short' => 'b034', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SourceName' => ['short' => 'x330', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SourceTitle' => ['short' => 'x428', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SourceType' => ['short' => 'x431', 'kind' => 'codelist', 'codelist' => '157', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationBundleName' => ['short' => 'specificationbundlename', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SpecificationBundleName'],
        'SpecificationBundleNameTypeName' => ['short' => 'x558', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationBundleNameValue' => ['short' => 'x559', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationDescription' => ['short' => 'x564', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationDetail' => ['short' => 'x560', 'kind' => 'codelist', 'codelist' => '248', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationFeature' => ['short' => 'specificationfeature', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SpecificationFeature'],
        'SpecificationFeatureDescription' => ['short' => 'x563', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationFeatureType' => ['short' => 'x561', 'kind' => 'codelist', 'codelist' => '249', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SpecificationFeatureValue' => ['short' => 'x562', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'StartDate' => ['short' => 'b324', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'StartTime' => ['short' => 'x542', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Stock' => ['short' => 'stock', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Stock'],
        'StockQuantityCode' => ['short' => 'j297', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'StockQuantityCoded' => ['short' => 'stockquantitycoded', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\StockQuantityCoded'],
        'StockQuantityCodeType' => ['short' => 'j293', 'kind' => 'codelist', 'codelist' => '70', 'releases' => ['3.0', '3.1'], 'class' => null],
        'StockQuantityCodeTypeName' => ['short' => 'j296', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'StreetAddress' => ['short' => 'x552', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'StudyBibleType' => ['short' => 'b389', 'kind' => 'codelist', 'codelist' => '84', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Subject' => ['short' => 'subject', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Subject'],
        'SubjectCode' => ['short' => 'b069', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SubjectDate' => ['short' => 'subjectdate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SubjectDate'],
        'SubjectDateRole' => ['short' => 'x534', 'kind' => 'codelist', 'codelist' => '177', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SubjectDescription' => ['short' => 'x591', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'SubjectHeadingText' => ['short' => 'b070', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SubjectSchemeIdentifier' => ['short' => 'b067', 'kind' => 'codelist', 'codelist' => '27', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SubjectSchemeName' => ['short' => 'b171', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SubjectSchemeVersion' => ['short' => 'b068', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Subtitle' => ['short' => 'b029', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SuffixToKey' => ['short' => 'b248', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplementManifest' => ['short' => 'supplementmanifest', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplementManifest'],
        'Supplier' => ['short' => 'supplier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Supplier'],
        'SupplierCodeType' => ['short' => 'x458', 'kind' => 'codelist', 'codelist' => '165', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplierCodeTypeName' => ['short' => 'x513', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplierCodeValue' => ['short' => 'x459', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplierIdentifier' => ['short' => 'supplieridentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplierIdentifier'],
        'SupplierIDType' => ['short' => 'j345', 'kind' => 'codelist', 'codelist' => '92', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplierName' => ['short' => 'j137', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplierOwnCoding' => ['short' => 'supplierowncoding', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplierOwnCoding'],
        'SupplierRole' => ['short' => 'j292', 'kind' => 'codelist', 'codelist' => '93', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplyContact' => ['short' => 'supplycontact', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplyContact'],
        'SupplyContactIdentifier' => ['short' => 'supplycontactidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplyContactIdentifier'],
        'SupplyContactIDType' => ['short' => 'x538', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplyContactName' => ['short' => 'x539', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplyContactRole' => ['short' => 'x537', 'kind' => 'codelist', 'codelist' => '239', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplyDate' => ['short' => 'supplydate', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplyDate'],
        'SupplyDateRole' => ['short' => 'x461', 'kind' => 'codelist', 'codelist' => '166', 'releases' => ['3.0', '3.1'], 'class' => null],
        'SupplyDetail' => ['short' => 'supplydetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupplyDetail'],
        'SupportingResource' => ['short' => 'supportingresource', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\SupportingResource'],
        'Tax' => ['short' => 'tax', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Tax'],
        'TaxableAmount' => ['short' => 'x473', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TaxAmount' => ['short' => 'x474', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TaxExempt' => ['short' => 'x546', 'kind' => 'flag', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TaxRateCode' => ['short' => 'x471', 'kind' => 'codelist', 'codelist' => '62', 'releases' => ['3.0', '3.1'], 'class' => null],
        'TaxRatePercent' => ['short' => 'x472', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TaxType' => ['short' => 'x470', 'kind' => 'codelist', 'codelist' => '171', 'releases' => ['3.0', '3.1'], 'class' => null],
        'TelephoneNumber' => ['short' => 'j270', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Territory' => ['short' => 'territory', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Territory'],
        'Text' => ['short' => 'd104', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TextAuthor' => ['short' => 'd107', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TextContent' => ['short' => 'textcontent', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\TextContent'],
        'TextItem' => ['short' => 'textitem', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\TextItem'],
        'TextItemIdentifier' => ['short' => 'textitemidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\TextItemIdentifier'],
        'TextItemIDType' => ['short' => 'b285', 'kind' => 'codelist', 'codelist' => '43', 'releases' => ['3.0', '3.1'], 'class' => null],
        'TextItemType' => ['short' => 'b290', 'kind' => 'codelist', 'codelist' => '42', 'releases' => ['3.0', '3.1'], 'class' => null],
        'TextSource' => ['short' => 'textsource', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.1'], 'class' => 'MirayS\Onix\Product\\TextSource'],
        'TextSourceCorporate' => ['short' => 'b374', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TextSourceDescription' => ['short' => 'x557', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TextSourceLink' => ['short' => 'x581', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.1'], 'class' => null],
        'TextType' => ['short' => 'x426', 'kind' => 'codelist', 'codelist' => '153', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ThesisPresentedTo' => ['short' => 'b369', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ThesisType' => ['short' => 'b368', 'kind' => 'codelist', 'codelist' => '72', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ThesisYear' => ['short' => 'b370', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TimeRun' => ['short' => 'timerun', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\TimeRun'],
        'TitleDetail' => ['short' => 'titledetail', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\TitleDetail'],
        'TitleElement' => ['short' => 'titleelement', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\TitleElement'],
        'TitleElementLevel' => ['short' => 'x409', 'kind' => 'codelist', 'codelist' => '149', 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitlePrefix' => ['short' => 'b030', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitlesAfterNames' => ['short' => 'b043', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitlesBeforeNames' => ['short' => 'b038', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitleStatement' => ['short' => 'x478', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitleText' => ['short' => 'b203', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitleType' => ['short' => 'b202', 'kind' => 'codelist', 'codelist' => '15', 'releases' => ['3.0', '3.1'], 'class' => null],
        'TitleWithoutPrefix' => ['short' => 'b031', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'ToLanguage' => ['short' => 'x413', 'kind' => 'codelist', 'codelist' => '74', 'releases' => ['3.0', '3.1'], 'class' => null],
        'ToQuantity' => ['short' => 'x514', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'TradeCategory' => ['short' => 'b384', 'kind' => 'codelist', 'codelist' => '12', 'releases' => ['3.0', '3.1'], 'class' => null],
        'UnnamedPersons' => ['short' => 'b249', 'kind' => 'codelist', 'codelist' => '19', 'releases' => ['3.0', '3.1'], 'class' => null],
        'UnpricedItemType' => ['short' => 'j192', 'kind' => 'codelist', 'codelist' => '57', 'releases' => ['3.0', '3.1'], 'class' => null],
        'Velocity' => ['short' => 'velocity', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Velocity'],
        'VelocityMetric' => ['short' => 'x504', 'kind' => 'codelist', 'codelist' => '216', 'releases' => ['3.0', '3.1'], 'class' => null],
        'VenueName' => ['short' => 'x551', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'VenueNote' => ['short' => 'x553', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'Website' => ['short' => 'website', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\Website'],
        'WebsiteDescription' => ['short' => 'b294', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'WebsiteLink' => ['short' => 'b295', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'WebsiteRole' => ['short' => 'b367', 'kind' => 'codelist', 'codelist' => '73', 'releases' => ['3.0', '3.1'], 'class' => null],
        'WorkIdentifier' => ['short' => 'workidentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => 'MirayS\Onix\Product\\WorkIdentifier'],
        'WorkIDType' => ['short' => 'b201', 'kind' => 'codelist', 'codelist' => '16', 'releases' => ['3.0', '3.1'], 'class' => null],
        'WorkRelationCode' => ['short' => 'x454', 'kind' => 'codelist', 'codelist' => '164', 'releases' => ['3.0', '3.1'], 'class' => null],
        'YearOfAnnual' => ['short' => 'b020', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0', '3.1'], 'class' => null],
        'AudienceCode' => ['short' => 'b073', 'kind' => 'codelist', 'codelist' => '28', 'releases' => ['3.0'], 'class' => null],
        'Conference' => ['short' => 'conference', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0'], 'class' => 'MirayS\Onix\Product\\Conference'],
        'ConferenceAcronym' => ['short' => 'b341', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'ConferenceDate' => ['short' => 'b054', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'ConferenceName' => ['short' => 'b052', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'ConferenceNumber' => ['short' => 'b053', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'ConferencePlace' => ['short' => 'b055', 'kind' => 'scalar', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'ConferenceRole' => ['short' => 'b051', 'kind' => 'codelist', 'codelist' => '20', 'releases' => ['3.0'], 'class' => null],
        'ConferenceSponsor' => ['short' => 'conferencesponsor', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0'], 'class' => 'MirayS\Onix\Product\\ConferenceSponsor'],
        'ConferenceSponsorIdentifier' => ['short' => 'conferencesponsoridentifier', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0'], 'class' => 'MirayS\Onix\Product\\ConferenceSponsorIdentifier'],
        'ConferenceSponsorIDType' => ['short' => 'b391', 'kind' => 'codelist', 'codelist' => '44', 'releases' => ['3.0'], 'class' => null],
        'ConferenceTheme' => ['short' => 'b342', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'CurrencyZone' => ['short' => 'x475', 'kind' => 'codelist', 'codelist' => '172', 'releases' => ['3.0'], 'class' => null],
        'DateFormat' => ['short' => 'j260', 'kind' => 'codelist', 'codelist' => '55', 'releases' => ['3.0'], 'class' => null],
        'EpubLicense' => ['short' => 'epublicense', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0'], 'class' => 'MirayS\Onix\Product\\EpubLicense'],
        'Gender' => ['short' => 'x524', 'kind' => 'codelist', 'codelist' => '229', 'releases' => ['3.0'], 'class' => null],
        'PromotionContact' => ['short' => 'k166', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'Reissue' => ['short' => 'reissue', 'kind' => 'composite', 'codelist' => null, 'releases' => ['3.0'], 'class' => 'MirayS\Onix\Product\\Reissue'],
        'ReissueDate' => ['short' => 'j365', 'kind' => 'date', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
        'ReissueDescription' => ['short' => 'j366', 'kind' => 'text', 'codelist' => null, 'releases' => ['3.0'], 'class' => null],
    ];

    public static function has(string $element): bool
    {
        return isset(self::ELEMENTS[$element]);
    }

    public static function get(string $element): ?array
    {
        return self::ELEMENTS[$element] ?? null;
    }

    public static function releases(string $element): array
    {
        return self::ELEMENTS[$element]['releases'] ?? [];
    }

    public static function isInRelease(string $element, string $release): bool
    {
        return in_array($release, self::ELEMENTS[$element]['releases'] ?? [], true);
    }

    public static function codeList(string $element): ?string
    {
        return self::ELEMENTS[$element]['codelist'] ?? null;
    }

    public static function all(): array
    {
        return self::ELEMENTS;
    }
}
